apiVersion: v2
name: noves-canton-app
description: Noves Data App for Canton validators
type: application
version: 4.0.4
appVersion: "4.0.4"
kubeVersion: ">=1.27.0-0"
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/changes: |
    - kind: added
      description: Initial Helm chart.
